---

- name: add disks to the specified VM
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter.server }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    datacenter: "{{ vcenter.datacenter }}"
    disk: "{{ additional_storage }}"
  delegate_to: localhost