---

- name: manage DNS records
  community.general.ipa_dnsrecord:
    ipa_host:        "{{ dns.server | mandatory }}"
    ipa_pass:        "{{ dns.password | mandatory }}"
    validate_certs:  "{{ dns.validate_certs | default('false') }}"
    zone_name:       "{{ record.zone | mandatory }}"
    record_name:     "{{ record.name | mandatory }}"
    record_value:    "{{ record.value | mandatory }}"
    record_type:     "{{ record.type | mandatory }}"
  loop_control:
    loop_var: record
  loop: "{{ dns.records }}"
  delegate_to: "{{ delegate_host }}"