---

- name: get the installer extracted on the local system
  block:
    - name: create extract directory
      ansible.builtin.file:
        path: /tmp/aap-installer
        state: directory
# https://stackoverflow.com/questions/984204/shell-command-to-tar-directory-excluding-certain-files-folders
    - name: extract the tower installer
      ansible.builtin.unarchive:
        src: /tmp/ansible-tower-setup-latest.tar.gz
        dest: /tmp/aap-installer/
      when:
        not dirty_extract

    - name: extract the tower installer (dirty)
      ansible.builtin.shell:
        cmd: tar -xzvf /tmp/ansible-tower-setup-latest.tar.gz --directory /tmp/aap-installer
      when:
        dirty_extract
  delegate_to: localhost