---

- name: check for existing tower install
  ansible.builtin.shell: /usr/bin/tower-manage check
  register: tower_check
  ignore_errors: true
  changed_when: false
  when:
    - "'tower' in groups"
    - inventory_hostname in groups['tower']

- name: include install tasks
  ansible.builtin.include_tasks:
    file: "{{ task_file }}"
  loop_control:
    loop_var: task_file
  loop:
    - download-installer.yml
    - extract-installer.yml
    - run-installer.yml
  when:
    - tower_check.failed